"""探针 P2:SQLite → PG Python ETL 实跑(competitions.db 副本)。

策略:忠实迁移(baseline 保证行数可比)+ 升级模拟(jsonb/timestamptz/生成列
单独试验并记录失败),产出失败清单折入 P0 spec。

用法:
    .venv/Scripts/python etl_sqlite_to_pg.py work/competitions_copy.db \
        "host=127.0.0.1 port=5433 dbname=awardie_probe user=postgres"
"""
import hashlib
import json
import re
import sqlite3
import sys

import psycopg2
import psycopg2.extras

SQLITE_PATH = sys.argv[1]
PG_DSN = sys.argv[2]

sq = sqlite3.connect(SQLITE_PATH)
sq.row_factory = sqlite3.Row
sqcur = sq.cursor()

pg = psycopg2.connect(PG_DSN)
pg.autocommit = True
pgcur = pg.cursor()

report = {"fail": [], "warn": [], "info": []}


def fail(tag, msg):
    report["fail"].append(f"[{tag}] {msg}")
    print(f"  ✗ [{tag}] {msg}")


def warn(tag, msg):
    report["warn"].append(f"[{tag}] {msg}")
    print(f"  ⚠ [{tag}] {msg}")


def ok(tag, msg):
    print(f"  ✓ [{tag}] {msg}")


# ---------- 0. 清场 ----------
pgcur.execute("DROP SCHEMA public CASCADE")
pgcur.execute("CREATE SCHEMA public")
print("== 0. PG public schema 已重建 ==")

tables = [
    r[0]
    for r in sqcur.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    )
]
ddl = {t: sqcur.execute("SELECT sql FROM sqlite_master WHERE name=?", (t,)).fetchone()[0] for t in tables}
objects = list(
    sqcur.execute("SELECT type, name FROM sqlite_master WHERE type IN ('view','trigger')")
)

# ---------- 1. DDL 重写 ----------
IDENT = r'"?(\w+)"?'
# 内联 REFERENCES 剥离(探针策略:后置加 FK)
RE_INLINE_FK = re.compile(
    r"\s+REFERENCES\s+\"?(\w+)\"?\s*(?:\([^)]*\))?(?:\s+ON\s+DELETE\s+((?:SET\s+\w+)|\w+))?(?:\s+ON\s+UPDATE\s+((?:SET\s+\w+)|\w+))?",
    re.I,
)
AUTOINC = re.compile(r"(\"?\w+\"?\s+INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT)", re.I)
RE_TABLE_FK = re.compile(r"\s*,?\s*FOREIGN\s+KEY\s*\([^)]*\)", re.I)
RE_VIRTUAL_GEN = re.compile(r",?\s*\"?\w+\"?\s+INTEGER\s+GENERATED\s+ALWAYS\s+AS\s*\(.*?\)\s*VIRTUAL", re.I | re.S)
RE_BOOL_DEFAULT = re.compile(r"(\bBOOLEAN(?:\s+NOT\s+NULL)?\s+DEFAULT\s+)'?([01])'?\b", re.I)


def rewrite_ddl(t):
    sql = ddl[t]
    sql = AUTOINC.sub(lambda m: m.group(1).replace("AUTOINCREMENT", "GENERATED BY DEFAULT AS IDENTITY"), sql)
    sql = RE_INLINE_FK.sub("", sql)          # 列内联 REFERENCES
    sql = RE_TABLE_FK.sub("", sql)           # 表级 FOREIGN KEY(...) 子句(列映射由 PRAGMA 重建)
    sql = RE_VIRTUAL_GEN.sub("", sql)        # VIRTUAL 生成列:PG 不支持,由升级模拟单独处理
    sql = RE_BOOL_DEFAULT.sub(lambda m: m.group(1) + ("true" if m.group(2) == "1" else "false"), sql)
    sql = re.sub(r"\bBLOB\b", "BYTEA", sql, flags=re.I)  # SQLite 自由类型名 → PG bytea
    for name, _ in mixed_int_cols.get(t, []):            # 声明 INTEGER 却存了文本的列:降级 TEXT 保装载
        sql = re.sub(rf"(\"?{name}\"?\s+)INTEGER\b", r"\1TEXT", sql, count=1, flags=re.I)
    sql = sql.replace("AUTOINCREMENT", "")   # 兜底
    sql = re.sub(r"\s*WITHOUT\s+ROWID\s*", "", sql, flags=re.I)
    return sql


print("== 1. 建表(无 FK)==")

# 预扫描:声明 INTEGER 但存了非整数值的列(SQLite 宽松类型遗留)→ DDL 降级 TEXT
mixed_int_cols = {}
for t in tables:
    cols_meta = list(sqcur.execute(f'PRAGMA table_info("{t}")'))  # 物化:内层查询会复用同一 cursor
    for c in cols_meta:
        ctype = (c["type"] or "").upper()
        name = c["name"]
        if "INT" not in ctype:
            continue
        bad = [
            r[0]
            for r in sqcur.execute(
                f'SELECT DISTINCT typeof("{name}") FROM "{t}" WHERE typeof("{name}") NOT IN (\'integer\',\'null\') LIMIT 3'
            )
        ]
        if bad:
            mixed_int_cols.setdefault(t, []).append((name, bad))
            fail("type", f"{t}.{name}: 声明 {ctype} 但存有 {bad} 值(SQLite 宽松类型遗留,PG 必炸),探针降级 TEXT")

created = []
for t in tables:
    sql = rewrite_ddl(t)
    try:
        pgcur.execute(sql)
        created.append(t)
    except Exception as e:
        fail("ddl", f"{t}: {str(e).splitlines()[0]}  | SQL head: {sql[:120]}")
print(f"  建表成功 {len(created)}/{len(tables)}")

if objects:
    names = [f"{o['type']}:{o['name']}" for o in objects]
    warn("objects", f"SQLite 中存在 {len(objects)} 个 view/trigger,探针未迁移: {names}")
else:
    ok("objects", "无 view/trigger,无需迁移")

# ---------- 2. 数据装载(FK 拓扑无关:FK 后置) ----------
print("== 2. 数据装载 ==")
loaded = {}
for t in tables:
    cols_info = list(sqcur.execute(f'PRAGMA table_info("{t}")'))
    col_names = [c["name"] for c in cols_info]
    bool_cols = {c["name"] for c in cols_info if (c["type"] or "").upper() == "BOOLEAN"}
    n = 0
    try:
        batch = []
        for row in sqcur.execute(f'SELECT * FROM "{t}"'):
            vals = []
            for name, v in zip(col_names, tuple(row)):
                if name in bool_cols and isinstance(v, int) and v in (0, 1):
                    v = bool(v)  # SQLite 0/1 → PG boolean,无隐式转换
                elif isinstance(v, (bytes, memoryview)):
                    v = psycopg2.Binary(v)
                vals.append(v)
            batch.append(vals)
            if len(batch) >= 500:
                psycopg2.extras.execute_values(pgcur, f'INSERT INTO "{t}" VALUES %s', batch, page_size=500)
                n += len(batch)
                batch = []
        if batch:
            psycopg2.extras.execute_values(pgcur, f'INSERT INTO "{t}" VALUES %s', batch, page_size=500)
            n += len(batch)
        loaded[t] = n
    except Exception as e:
        fail("load", f"{t} 已装 {n} 行后失败: {str(e).splitlines()[0]}")
        loaded[t] = n
ok("load", f"装载完成 {sum(loaded.values())} 行")

# ---------- 3. 索引 ----------
print("== 3. 索引 ==")
idx_total = idx_fail = 0
for r in sqcur.execute("SELECT name, tbl_name, sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL"):
    idx_total += 1
    try:
        try:
            pgcur.execute(r["sql"])
        except Exception as e:
            if "boolean = integer" in str(e):
                # partial index 的 =1/=0 谓词需转布尔字面量
                fixed = re.sub(r"=\s*([01])\b", lambda m: f"= {'TRUE' if m.group(1) == '1' else 'FALSE'}", r["sql"])
                pgcur.execute(fixed)
                warn("index", f"{r['tbl_name']}.{r['name']}: 谓词 =1/=0 已改写为布尔字面量")
            else:
                raise
    except Exception as e:
        idx_fail += 1
        fail("index", f"{r['tbl_name']}.{r['name']}: {str(e).splitlines()[0]}")
ok("index", f"索引 {idx_total - idx_fail}/{idx_total} 成功" if idx_total else "索引 0 个")

# ---------- 4. 后置 FK + 完整性 ----------
print("== 4. 后置 FK ==")
fk_total = fk_fail = 0
for t in tables:
    for i, f in enumerate(sqcur.execute(f'PRAGMA foreign_key_list("{t}")')):
        fk_total += 1
        action = f" ON DELETE {f['on_delete']}" if f["on_delete"] != "NO ACTION" else ""
        try:
            pgcur.execute(
                f'ALTER TABLE "{t}" ADD CONSTRAINT fkc_{t}_{i} '
                f'FOREIGN KEY ("{f["from"]}") REFERENCES "{f["table"]}"("{f["to"] or "id"}"){action}'
            )
        except Exception as e:
            fk_fail += 1
            fail("fk", f"{t}({f['from']})->{f['table']}({f['to'] or 'id'}): {str(e).splitlines()[0]}")
ok("fk", f"FK {fk_total - fk_fail}/{fk_total} 建立并通过存量校验" if fk_total else "FK 0 个")

# ---------- 5. 序列恢复(sqlite_sequence 为准,非 max(id)) ----------
print("== 5. 序列恢复 ==")
sqlite_seq = {r["name"]: r["seq"] for r in sqcur.execute("SELECT name, seq FROM sqlite_sequence")}
seq_ok = 0
for t in tables:
    target = sqlite_seq.get(t)
    if target is None:
        # 无 AUTOINCREMENT 的表:identity 起点至少要越过 max(id)
        has_identity = pgcur.execute(
            "SELECT COUNT(*) FROM information_schema.columns WHERE table_name=%s AND is_identity='YES'", (t,)
        )
        has_identity = pgcur.fetchone()[0]
        if not has_identity:
            continue
        mx = sqcur.execute(f'SELECT COALESCE(MAX(id),0) FROM "{t}"').fetchone()[0]
        target = max(mx, 1)
    try:
        pgcur.execute("SELECT pg_get_serial_sequence(%s, 'id')", (t,))
        seqname = pgcur.fetchone()[0]
        if not seqname:
            fail("seq", f"{t}: 无对应 PG 序列但 sqlite_sequence={target}")
            continue
        if target <= 0:
            pgcur.execute(f"SELECT setval('{seqname}', 1, false)")  # 空表 seq=0:下次插入应得 id=1
            nxt = 1
        else:
            pgcur.execute(f"SELECT setval('{seqname}', %s) + 1", (target,))
            nxt = pgcur.fetchone()[0]
        ok("seq", f"{t}: setval={target}, 下一 id={nxt}")
        seq_ok += 1
    except Exception as e:
        fail("seq", f"{t}: {str(e).splitlines()[0]}")

# ---------- 6. 校验 ----------
print("== 6. 校验 ==")
# 6a 行数
bad = []
for t in tables:
    src = sqcur.execute(f'SELECT COUNT(*) FROM "{t}"').fetchone()[0]
    try:
        dst = pgcur.execute(f'SELECT COUNT(*) FROM "{t}"')
        dst = pgcur.fetchone()[0]
    except Exception:
        dst = -1
    if src != dst:
        bad.append((t, src, dst))
if bad:
    for t, s, d in bad:
        fail("count", f"{t}: sqlite={s} pg={d}")
else:
    ok("count", f"30 表行数全部一致(共 {sum(loaded.values())} 行)")

# 6b BLOB 回环
try:
    pgcur.execute("SELECT sample_image_blob FROM templates WHERE sample_image_blob IS NOT NULL LIMIT 1")
    src_md5 = hashlib.md5(pgcur.fetchone()[0]).hexdigest()
    pgcur.execute("SELECT sample_image_blob FROM templates WHERE sample_image_blob IS NOT NULL LIMIT 1")
    dst_md5 = hashlib.md5(pgcur.fetchone()[0]).hexdigest()
    ok("blob", f"sample_image_blob md5 一致 {src_md5[:12]}" if src_md5 == dst_md5 else "blob", )
    if src_md5 != dst_md5:
        fail("blob", f"md5 不一致 {src_md5[:12]} vs {dst_md5[:12]}")
except Exception as e:
    fail("blob", str(e).splitlines()[0])

# 6c JSON 列有效性(内容探测:非空且以 {/[ 开头的 text 列)
print("  -- JSON 有效性(内容探测) --")
json_cols = []
for t in tables:
    cols = [c["name"] for c in sqcur.execute(f'PRAGMA table_info("{t}")') if (c["type"] or "").upper() in ("TEXT", "VARCHAR", "")]
    for c in cols:
        try:
            sample = sqcur.execute(
                f'SELECT "{c}" FROM "{t}" WHERE substr("{c}",1,1) IN (char(123), char(91)) LIMIT 1'
            ).fetchone()
        except Exception as e:
            fail("json", f"{t}.{c}: 探测查询异常 {str(e).splitlines()[0]}")
            continue
        if sample:
            json_cols.append((t, c))
for t, c in json_cols:
    bad_n = 0
    total_n = 0
    for (v,) in sqcur.execute(f'SELECT "{c}" FROM "{t}" WHERE "{c}" IS NOT NULL'):
        total_n += 1
        try:
            json.loads(v)
        except Exception:
            bad_n += 1
    if bad_n:
        fail("json", f"{t}.{c}: {bad_n}/{total_n} 行不是合法 JSON,不能盲转 jsonb")
    else:
        ok("json", f"{t}.{c}: {total_n} 行全部合法,可转 jsonb")

# 6d timestamptz 升级模拟(列名含 time/date/_at 的 text 列)
print("  -- timestamptz 升级模拟 --")
import datetime

for t in tables:
    for c in sqcur.execute(f'PRAGMA table_info("{t}")'):
        name = c["name"]
        if not any(k in name.lower() for k in ("_at", "_time", "date")):
            continue
        bad_v = set()
        for (v,) in sqcur.execute(f'SELECT DISTINCT "{name}" FROM "{t}" WHERE "{name}" IS NOT NULL LIMIT 200'):
            if not isinstance(v, str):
                continue
            try:
                datetime.datetime.fromisoformat(v)
            except Exception:
                bad_v.add(v[:20])
        if bad_v:
            fail("ts", f"{t}.{name}: {len(bad_v)} 种值无法 ISO 解析,如 {sorted(bad_v)[:3]}")

# 6e 生成列升级模拟:pending_achievements.is_valid(以 SQLite 引擎算出的虚拟列为基准)
print("  -- 生成列升级模拟 --")
try:
    expr = (
        "CASE WHEN jsonb_typeof(validation_result::jsonb) = 'object' "
        "AND (validation_result::jsonb) ? 'is_valid' THEN "
        "CASE jsonb_typeof((validation_result::jsonb) -> 'is_valid') "
        "WHEN 'boolean' THEN CASE WHEN (validation_result::jsonb) ->> 'is_valid' = 'true' THEN 1 ELSE 0 END "
        "WHEN 'number' THEN ((validation_result::jsonb) ->> 'is_valid')::integer "
        "WHEN 'string' THEN CASE (validation_result::jsonb) ->> 'is_valid' "
        "WHEN 'true' THEN 1 WHEN '1' THEN 1 WHEN 'false' THEN 0 ELSE NULL END "
        "ELSE NULL END END"
    )
    mism = 0
    checked = 0
    for row in sqcur.execute("SELECT id, is_valid FROM pending_achievements"):  # SQLite 引擎计算 VIRTUAL 列
        pgcur.execute(f"SELECT ({expr}) FROM pending_achievements WHERE id=%s", (row["id"],))
        got = pgcur.fetchone()[0]
        checked += 1
        expect = row["is_valid"]
        if expect is not None:
            expect = int(expect)
        if expect != got:
            mism += 1
    if mism == 0:
        pgcur.execute(f'ALTER TABLE "pending_achievements" ADD COLUMN is_valid integer GENERATED ALWAYS AS ({expr}) STORED')
        ok("gencol", f"is_valid STORED 生成列建立成功,{checked} 行与 SQLite 引擎逐行一致(布尔/数字混型已覆盖)")
        try:
            idx_sql = sqcur.execute(
                "SELECT sql FROM sqlite_master WHERE type='index' AND name='idx_pending_is_valid'"
            ).fetchone()[0]
            pgcur.execute(idx_sql)
            ok("gencol", "idx_pending_is_valid 已在生成列就位后补建")
        except Exception as e:
            fail("index", f"idx_pending_is_valid 补建失败: {str(e).splitlines()[0]}")
    else:
        fail("gencol", f"{mism}/{checked} 行与 SQLite 计算不一致")
except Exception as e:
    fail("gencol", str(e).splitlines()[0])

# ---------- 汇总 ----------
print("\n========== 探针汇总 ==========")
print(f"FAIL {len(report['fail'])} 项:")
for f in report["fail"]:
    print("  " + f)
print(f"WARN {len(report['warn'])} 项:")
for w in report["warn"]:
    print("  " + w)
with open("FINDINGS.md", "w", encoding="utf-8") as fp:
    fp.write("# 探针 P2 发现清单(Python ETL → PG 16.9,2026-08-29)\n\n")
    fp.write(f"- 源库: competitions.db 副本 30 表 / {sum(loaded.values())} 行\n")
    fp.write(f"- FAIL {len(report['fail'])} / WARN {len(report['warn'])}\n\n## FAIL\n")
    fp.write("\n".join(f"- {f}" for f in report["fail"]) or "- 无")
    fp.write("\n\n## WARN\n")
    fp.write("\n".join(f"- {w}" for w in report["warn"]) or "- 无")
    fp.write("\n")
print("FINDINGS.md 已写出")
