# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiServiceStub:
    """AI Worker 契约(v1 LangGraph 编排 1:1 保留,仅接口层 gRPC 化,N1 非目标)
    流式口径与探针 P1 结论一致:server-streaming 走 Nginx 需 grpc_read_timeout>=300s。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Extract = channel.unary_unary(
                '/awardie.ai.AiService/Extract',
                request_serializer=ai__service__pb2.ExtractRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ExtractResponse.FromString,
                _registered_method=True)
        self.ExtractAndReview = channel.unary_stream(
                '/awardie.ai.AiService/ExtractAndReview',
                request_serializer=ai__service__pb2.ExtractRequest.SerializeToString,
                response_deserializer=ai__service__pb2.WorkflowEvent.FromString,
                _registered_method=True)
        self.Ask = channel.unary_stream(
                '/awardie.ai.AiService/Ask',
                request_serializer=ai__service__pb2.AskRequest.SerializeToString,
                response_deserializer=ai__service__pb2.AnswerEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/awardie.ai.AiService/Health',
                request_serializer=ai__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=ai__service__pb2.HealthResponse.FromString,
                _registered_method=True)


class AiServiceServicer:
    """AI Worker 契约(v1 LangGraph 编排 1:1 保留,仅接口层 gRPC 化,N1 非目标)
    流式口径与探针 P1 结论一致:server-streaming 走 Nginx 需 grpc_read_timeout>=300s。
    """

    def Extract(self, request, context):
        """抽取:文件 → 结构化数据(unary,v1 framework.extract 同步语义)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractAndReview(self, request, context):
        """抽取+审核全链:流式过程事件(node 进度/答案增量)+ 最终审核结论(server-streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ask(self, request, context):
        """AI 问答(RAG):流式答案增量(server-streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """健康探针
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Extract': grpc.unary_unary_rpc_method_handler(
                    servicer.Extract,
                    request_deserializer=ai__service__pb2.ExtractRequest.FromString,
                    response_serializer=ai__service__pb2.ExtractResponse.SerializeToString,
            ),
            'ExtractAndReview': grpc.unary_stream_rpc_method_handler(
                    servicer.ExtractAndReview,
                    request_deserializer=ai__service__pb2.ExtractRequest.FromString,
                    response_serializer=ai__service__pb2.WorkflowEvent.SerializeToString,
            ),
            'Ask': grpc.unary_stream_rpc_method_handler(
                    servicer.Ask,
                    request_deserializer=ai__service__pb2.AskRequest.FromString,
                    response_serializer=ai__service__pb2.AnswerEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ai__service__pb2.HealthRequest.FromString,
                    response_serializer=ai__service__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'awardie.ai.AiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('awardie.ai.AiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiService:
    """AI Worker 契约(v1 LangGraph 编排 1:1 保留,仅接口层 gRPC 化,N1 非目标)
    流式口径与探针 P1 结论一致:server-streaming 走 Nginx 需 grpc_read_timeout>=300s。
    """

    @staticmethod
    def Extract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/awardie.ai.AiService/Extract',
            ai__service__pb2.ExtractRequest.SerializeToString,
            ai__service__pb2.ExtractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractAndReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/awardie.ai.AiService/ExtractAndReview',
            ai__service__pb2.ExtractRequest.SerializeToString,
            ai__service__pb2.WorkflowEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/awardie.ai.AiService/Ask',
            ai__service__pb2.AskRequest.SerializeToString,
            ai__service__pb2.AnswerEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/awardie.ai.AiService/Health',
            ai__service__pb2.HealthRequest.SerializeToString,
            ai__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
