# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streamer.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'streamer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0estreamer.proto\x12\x05probe\"F\n\tStreamReq\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x13\n\x0binterval_ms\x18\x02 \x01(\x05\x12\x15\n\rpayload_bytes\x18\x03 \x01(\x05\"1\n\x05\x44\x65lta\x12\x0b\n\x03seq\x18\x01 \x01(\x05\x12\n\n\x02ts\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x32l\n\x08Streamer\x12\x30\n\x0cStreamDeltas\x12\x10.probe.StreamReq\x1a\x0c.probe.Delta0\x01\x12.\n\nStreamSlow\x12\x10.probe.StreamReq\x1a\x0c.probe.Delta0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streamer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMREQ']._serialized_start=25
  _globals['_STREAMREQ']._serialized_end=95
  _globals['_DELTA']._serialized_start=97
  _globals['_DELTA']._serialized_end=146
  _globals['_STREAMER']._serialized_start=148
  _globals['_STREAMER']._serialized_end=256
# @@protoc_insertion_point(module_scope)
