# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import streamer_pb2 as streamer__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in streamer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamerStub:
    """探针 P1:gRPC server-streaming 经 Nginx 透传验证
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamDeltas = channel.unary_stream(
                '/probe.Streamer/StreamDeltas',
                request_serializer=streamer__pb2.StreamReq.SerializeToString,
                response_deserializer=streamer__pb2.Delta.FromString,
                _registered_method=True)
        self.StreamSlow = channel.unary_stream(
                '/probe.Streamer/StreamSlow',
                request_serializer=streamer__pb2.StreamReq.SerializeToString,
                response_deserializer=streamer__pb2.Delta.FromString,
                _registered_method=True)


class StreamerServicer:
    """探针 P1:gRPC server-streaming 经 Nginx 透传验证
    """

    def StreamDeltas(self, request, context):
        """短流:20 个 delta,间隔 200ms(验证缓冲行为)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSlow(self, request, context):
        """长 idle 流:3 个 delta,间隔 35s(验证 grpc_read_timeout 断流)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamDeltas': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamDeltas,
                    request_deserializer=streamer__pb2.StreamReq.FromString,
                    response_serializer=streamer__pb2.Delta.SerializeToString,
            ),
            'StreamSlow': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSlow,
                    request_deserializer=streamer__pb2.StreamReq.FromString,
                    response_serializer=streamer__pb2.Delta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'probe.Streamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('probe.Streamer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Streamer:
    """探针 P1:gRPC server-streaming 经 Nginx 透传验证
    """

    @staticmethod
    def StreamDeltas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/probe.Streamer/StreamDeltas',
            streamer__pb2.StreamReq.SerializeToString,
            streamer__pb2.Delta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSlow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/probe.Streamer/StreamSlow',
            streamer__pb2.StreamReq.SerializeToString,
            streamer__pb2.Delta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
